services:
  - type: web
    name: rice-leaf-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
